# حط التوكنز بتاعتك هنا لو عايز تخفيها من الكود
# لو سبتها فاضية، التطبيق هيستخدم القيم الافتراضية اللي في الكود

YOUR_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Il9pZCI6IjY5Y2VlY2Y1MTk3Zjg0NWZjOWZlZGU1YyJ9LCJpYXQiOjE3NzUxNjg3NTcsImV4cCI6MTc3Nzc2MDc1N30.nIKi8ohQAYsAVXQL9_rlRUr93TDg-G-DVOCQOrRdOtY"
TELEGRAM_BOT_TOKEN = "8261610629:AAFs-el5LK236x1xkDuUM8k-6NOi81X4FU8"
TELEGRAM_CHAT_ID = "1690550033"
